    char ques[30][50]= {"0.This is the name of a city",
    "1.This is the name of a country",
    "2.It is an animal",
    "3.It is a colour",
    "4.It is a bird",
    "5.It is a flower",
    "6.It is a fruit",
    "7.It is a vegetable",
    "8.It is a royal place",
    "9.It is an insect",
    "10.It is a historical place",
    "11.It is a fairy tale character",
    "12.It is related with desert",
    "13.It is a sea animal",
    "14.Clue:Sharp thing,used in war",
    "15.It is a temporary shelter",
    "16.It is an insect,Clue:Light",
    "17.Clue:Ice",
    "18.It is a spice ingredient",
    "19.It is an institution",
    "20.It is a source of water",
    "21.It is related with time",
    "22.It is related with date",
    "23.It is related with word",
    "24.It is related with sky",
    "25.Clue:Passer",
    "26.Clue:Thunder",
    "27.It is a reptile",
    "28.It is related with rain",
    "29.It is a disaster"};
    char word[30][15]= {"dhaka",
    "somalia",
    "elephant",
    "green",
    "parrot",
    "marigold",
    "orange",
    "carrot",
    "palace",
    "butterfly",
    "pyramid",
    "mermaid",
    "oasis",
    "whale",
    "sword",
    "tent",
    "glowworm",
    "freeze",
    "garlic",
    "university",
    "ocean",
    "clock",
    "calender",
    "dictionary",
    "cloud",
    "street",
    "storm",
    "crocodile",
    "umbrella",
    "flood"};
    char temp[30][15]= {"-----",
    "-------",
    "--------",
    "-----",
    "------",
    "--------",
    "------",
    "------",
    "------",
    "---------",
    "-------",
    "-------",
    "-----",
    "-----",
    "-----",
    "----",
    "--------",
    "------",
    "------",
    "----------",
    "-----",
    "-----",
    "--------",
    "----------",
    "-----",
    "------",
    "-----",
    "---------",
    "--------",
    "-----"};
