    char ques[30][50]= {"0.This is the name of a city",
    "1.This is the name of a country",
    "2.It is an animal",
    "3.It is a colour",
    "4.It is a bird",
    "5.It is a flower",
    "6.It is a fruit",
    "7.It is a vegetable",
    "8.It is a language",
    "9.It is an insect",
    "10.It is the name of a scientist",
    "11.It is a fairy tale character",
    "12.It is related with desert",
    "13.It is a sea animal",
    "14.It is the name of a river",
    "15.It is the name of a month",
    "16.It is a study related material",
    "17.It is a fish",
    "18.It is a spice ingredient",
    "19.It is an institution",
    "20.It is a source of water",
    "21.It is an electronic device",
    "22.It is a sport",
    "23.It is related with word",
    "24.It is related with sky",
    "25.It is a musical instrument",
    "26.It is a part of body",
    "27.It is a reptile",
    "28.It is the name of a grain",
    "29.It is a disaster"};
    char word[30][5][15]= {"dhaka","mymensingh","chittagong","sylhet","rajshahi",
    "somalia","australia","nepal","bangladesh","china",
    "elephant","deer","tiger","cow","cat",
    "green","red","blue","purple","pink",
    "parrot","owl","cuckoo","pigeon","crow",
    "marigold","rose","lily","tuberose","waterlily",
    "orange","mango","grape","jackfruit","apple",
    "carrot","tomato","potato","papaya","chili",
    "bangla","english","spanish","french","arabic",
    "butterfly","glowworm","fly","spider","gnat",
    "einstein","newton","galileo","darwin","grahambell",
    "mermaid","cinderella","snowwhite","giant","ghost",
    "oasis","sand","camel","mirage","heat",
    "whale","crab","dolphin","jellyfish","octopus",
    "padma","meghna","jamuna","tista","karnafuly",
    "january","february","march","may","june",
    "book","pen","pencil","eraser","compass",
    "catfish","carp","salmon","hilsha","tuna",
    "garlic","onion","turmeric","ginger","coriander",
    "university","school","collage","hospital","office",
    "ocean","sea","river","pond","fountain",
    "computer","television","phone","fridge","camera",
    "cricket","football","hockey","tennis","volleyball",
    "dictionary","vocabulary","letter","sentence","alphabet",
    "cloud","rainbow","star","moon","sun",
    "flute","harmonium","guitar","tabla","violin"
    "ear","eye","stomach","hand","leg",
    "crocodile","lizard","turtle","chameleon","snake",
    "rice","wheat","barley","corn","mustard",
    "flood","earthquake","storm","cyclone","tornado"};
    char temp[30][5][15]= {"-----","----------","----------","------","---------",
    "-------","---------","-----","----------","-----",
    "--------","----","-----","---","---",
    "-----","---","----","------","----",
    "------","---","------","------","----",
    "--------","----","----","--------","---------",
    "------","-----","-----","---------","-----",
    "------","------","------","------","-----",
    "------","-------","-------","------","------",
    "---------","--------","---","------","----",
    "--------","------","-------","------","----------",
    "-------","----------","---------","-----","-----",
    "-----","----","-----","------","----",
    "-----","----","-------","---------","-------",
    "-----","------","------","-----","---------",
    "-------","--------","-----","---","----",
    "----","---","------","------","-------",
    "-------","----","------","------","----",
    "------","-----","---------","------","---------",
    "----------","------","-------","--------","------",
    "-----","---","-----","----","--------",
    "--------","----------","-----","------","------",
    "-------","--------","------","------","----------",
    "----------","----------","------","--------","--------",
    "-----","-------","----","----","---",
    "-----","---------","------","-----","------",
    "---","---","-------","----","---",
    "---------","------","------","---------","-----",
    "----","-----","------","----","-------",
    "-----","----------","-----","-------","-------"};
